### ISSUE TITLE
Outputs not working after intialy working

### ISSUE THREAD

**Issue by Denisp5907** [vitormhenrique/OctoPrint-Enclosure#478]
The plugin worked perfectly after initial installation but then the following day none of the buttons work. They are there on the Nav bar and in the plugin tab but when pressed they don't change the status.
![image](https://user-images.githubusercontent.com/29822249/153755540-22ef16fd-7323-4202-8c7d-68653eb2aeeb.png)

Octoprint Log:-
2022-02-12 18:02:04,759 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octop2022-02-12 18:02:02,152 - octoprint.plugins.enclosure - WARNING - An exception of type RuntimeError occurred on log_error. Arg$
('You must setup() the GPIO channel first',)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_enclosure/__init__.py", line 953, in update_ui_outputs
    val = GPIO.input(pin) if not output['active_low'] else (not GPIO.input(pin))
RuntimeError: You must setup() the GPIO channel first
2022-02-12 18:02:02,152 - octoprint.plugins.enclosure - WARNING - An exception of type RuntimeError occurred on log_error. Arguments:
('You must setup() the GPIO channel first',)
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_enclosure/__init__.py", line 953, in update_ui_outputs
    val = GPIO.input(pin) if not output['active_low'] else (not GPIO.input(pin))
RuntimeError: You must setup() the GPIO channel first

**Comment by Denisp5907** [comment]
Oddly I have this working again. I've disabled OctoPod and uninstalled a SmartFilamentsensor plugin then restarted the raspberry pi.
