### ISSUE TITLE
Error with Neopixel after upgrade

### ISSUE THREAD

**Issue by vitormhenrique** [vitormhenrique/OctoPrint-Enclosure#98]
Getting the following error after upgrading the plugin:

```
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/neopixel_direct.py", line 1, in <module>
    from neopixel import *
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/neopixel.py", line 21, in <module>
    bus.write_i2c_block_data(address,0, data)
IOError: [Errno 121] Remote I/O error
```

**Comment by vitormhenrique** [comment]
This issue is caused because I named one script with the same name as a python library.

To fix the issue remove old files from the installation by runing:

```
rm -rf /home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/neopixel.py
rm -rf /home/pi/oprint/lib/python2.7/site-packages/octoprint_enclosure/neopixel.pyc 

```
